"use client";
import { useRouter } from "next/navigation";
import { useMemo } from "react";
import EntityTable from "./EntityTable";
import type { Column } from "./DataTable";
import StatusBadge from "./StatusBadge";
import StatCard from "./StatCard";
import Tabs from "./Tabs";
import { PageHeader, UserLink, IdLink, NotFoundCard } from "./ui";
import { useAdminData } from "@/context/AdminDataContext";
import { ibStats } from "@/lib/selectors";
import { IB_RANKS, IB_TYPES } from "@/data/ibs";
import { fmtDate, money, num } from "@/lib/format";
import type { IB, IBRank, IBType } from "@/types/admin";

const SLUGS: Record<string, { title: string; sub: string; test: (i: IB) => boolean }> = {
  all: { title: "All IBs", sub: "Every introducing broker with type, rank and performance.", test: () => true },
  "rebate-link": { title: "Rebate Link IB", sub: "IBs earning a rebate per lot from referred clients.", test: (i) => i.type === "Rebate Link" },
  "revenue-link": { title: "Revenue Link IB", sub: "IBs earning a share of revenue generated by referred clients.", test: (i) => i.type === "Revenue Link" },
  ...Object.fromEntries(IB_RANKS.map((r) => [r.toLowerCase(), { title: `${r} IB`, sub: `All IBs currently at ${r} rank.`, test: (i: IB) => i.rank === r }])),
};
const TAB_HREF: Record<string, string> = { all: "/ib", "rebate-link": "/ib/rebate-link", "revenue-link": "/ib/revenue-link", ...Object.fromEntries(IB_RANKS.map((r) => [r.toLowerCase(), `/ib/${r.toLowerCase()}`])) };

export default function IBTable({ slug: rawSlug = "all" }: { slug?: string }) {
  const slug = rawSlug === "started" ? "starter" : rawSlug; // legacy URL alias
  const d = useAdminData();
  const router = useRouter();
  const meta = SLUGS[slug];
  const rows = useMemo(() => (meta ? d.ibs.filter(meta.test).map((ib) => ({ ib, user: d.users.find((u) => u.id === ib.userId)!, ...ibStats(ib, d) })) : []), [d, meta]);
  if (!meta) return <NotFoundCard what="IB category" backHref="/ib" />;
  type Row = (typeof rows)[number];
  const columns: Column<Row>[] = [
    { key: "id", header: "IB ID", render: (r) => <IdLink href={`/ib/profile/${r.ib.id}`}>{r.ib.id}</IdLink>, sortValue: (r) => r.ib.id },
    { key: "uid", header: "User ID", render: (r) => <UserLink id={r.ib.userId} /> },
    { key: "name", header: "Name", render: (r) => <b>{r.user.name}</b>, sortValue: (r) => r.user.name },
    { key: "type", header: "IB Type", render: (r) => r.ib.type },
    { key: "rank", header: "IB Rank", render: (r) => <span className="ix-badge blue">{r.ib.rank}</span>, sortValue: (r) => IB_RANKS.indexOf(r.ib.rank) },
    { key: "ref", header: "Referred Users", align: "right", render: (r) => r.referredCount, sortValue: (r) => r.referredCount },
    { key: "act", header: "Active Users", align: "right", render: (r) => r.activeUsers, sortValue: (r) => r.activeUsers },
    { key: "rev", header: "Revenue", align: "right", render: (r) => money(r.revenue), sortValue: (r) => r.revenue },
    { key: "com", header: "Commission", align: "right", render: (r) => money(r.commission), sortValue: (r) => r.commission },
    { key: "st", header: "Status", render: (r) => <StatusBadge status={r.ib.status} /> },
    { key: "cr", header: "Created Date", render: (r) => fmtDate(r.ib.createdAt), sortValue: (r) => r.ib.createdAt },
    { key: "a", header: "Actions", render: (r) => <button className="ix-btn ix-btn-sm ix-btn-soft" onClick={(e) => { e.stopPropagation(); router.push(`/ib/profile/${r.ib.id}`); }}><i className="ti ti-eye" />View</button> },
  ];
  return (
    <>
      <PageHeader title={meta.title} subtitle={meta.sub} />
      <div style={{ marginBottom: 18 }}>
        <Tabs active={slug} onChange={(id) => router.push(TAB_HREF[id])} tabs={[{ id: "all", label: "All" }, ...IB_TYPES.map((t) => ({ id: t.toLowerCase().replace(" ", "-"), label: t })), ...IB_RANKS.map((r) => ({ id: r.toLowerCase(), label: r }))]} />
      </div>
      <div className="ix-grid c4" style={{ marginBottom: 18 }}>
        <StatCard label="IBs" value={num(rows.length)} icon="ti-network" />
        <StatCard label="Referred users" value={num(rows.reduce((s, r) => s + r.referredCount, 0))} icon="ti-users" tone="green" />
        <StatCard label="Total revenue" value={money(rows.reduce((s, r) => s + r.revenue, 0))} icon="ti-coin" tone="amber" />
        <StatCard label="Total commission" value={money(rows.reduce((s, r) => s + r.commission, 0))} icon="ti-percentage" />
      </div>
      <EntityTable
        rows={rows} rowKey={(r) => r.ib.id} columns={columns} onRowClick={(r) => router.push(`/ib/profile/${r.ib.id}`)}
        searchText={(r) => `${r.ib.id} ${r.ib.userId} ${r.user.name}`} searchPlaceholder="Search IB ID, user ID or name…"
        filters={[{ label: "Type", options: IB_TYPES as unknown as string[], get: (r) => r.ib.type as IBType }, { label: "Rank", options: IB_RANKS as unknown as string[], get: (r) => r.ib.rank as IBRank }, { label: "Status", options: ["Active", "Suspended"], get: (r) => r.ib.status }]}
        dateGet={(r) => r.ib.createdAt} dateLabel="Created" exportName={`ib-${slug}`}
        exportRow={(r) => ({ "IB ID": r.ib.id, "User ID": r.ib.userId, Name: r.user.name, Type: r.ib.type, Rank: r.ib.rank, Referred: r.referredCount, Active: r.activeUsers, Revenue: r.revenue.toFixed(2), Commission: r.commission.toFixed(2), Status: r.ib.status })}
      />
    </>
  );
}
